create table users
(
    id      bigint auto_increment,
    name    varchar(50),
    balance int,
    primary key (id)
);

create table user_transaction
(
    id               bigint auto_increment,
    user_id          bigint,
    amount           int,
    transaction_date timestamp,
    primary key (id),
    foreign key (user_id) references users (id) on delete cascade
);


-- create table users
-- (
--     id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     name    varchar(50),
--     balance int
-- );
--
-- create table user_transaction
-- (
--     id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     user_id          bigint,
--     amount           int,
--     transaction_date timestamp
-- );
